let prevLeadCounts = {};
let leadAlertInitialized = false;
let alertViewerName = '';
let alertViewerYtelId = '';

// ── TIER 1: First lead — Breaking the Ice (100 quotes) ──
const QUOTES_FIRST_LEAD = [
  "That's how you break the ice — now keep the heat coming!",
  "First one is always the hardest. You made it look easy!",
  "The scoreboard is open! Now let's stack 'em up.",
  "Ice broken! Now let's turn up the temperature.",
  "First lead on the board — you set the tone!",
  "That's your foot in the door. Now kick it wide open!",
  "One down. The shift just got interesting.",
  "Good job getting off the mark — the momentum is yours now.",
  "You cracked it open! Keep that same energy dialing.",
  "First blood! The board belongs to you now.",
  "Great start — the hardest lead is always the first one.",
  "You're on the board! Every empire starts with one brick.",
  "That first transfer is the spark. Now light the whole room up.",
  "Boom! You're alive on the leaderboard — keep building!",
  "The ice is broken. Now let's make some waves.",
  "Lead one secured. Time to turn that into a streak.",
  "You got the first one — that's the hardest part done!",
  "Off the mark and rolling! Don't stop now.",
  "First transfer in the bag. The dial tone is your best friend.",
  "Nice work breaking through! Your next call is already waiting.",
  "That's one for the board! Keep your head down and keep dialing.",
  "One lead is all the proof you need — now get another!",
  "You broke the seal. Time to flood the board!",
  "First transfer secured! Confidence is built one call at a time.",
  "You kicked the door open. Now walk through it again and again.",
  "Step one is always the toughest. Step one: done. Now go!",
  "The board just got your name on it. Let's keep it there!",
  "That first dial that paid off — remember this feeling!",
  "You opened your account! Time to make a deposit on the next one.",
  "First transfer of the day — you're already ahead of where you started.",
  "Look at you! One lead in and already proving yourself. Keep it up.",
  "The silence before the first lead is the hardest part. You pushed through it!",
  "That's number one — now your only job is to make it not the last.",
  "You rang the bell! Don't stop swinging.",
  "First lead locked in. The rest of the shift is wide open.",
  "You're on the board and that's all that matters right now. Push for two!",
  "One lead changes everything. Now go change everything again.",
  "That first 'yes' hits different. Chase it again and again.",
  "The shift officially started when that lead transferred. Let's go!",
  "First lead of the day — you're running laps around those who haven't started.",
  "You got the ball rolling. Now keep it rolling, harder and faster.",
  "Don't stop at one. That first transfer was just the warm-up!",
  "Every rep on that board started with one. You just did yours.",
  "Great job! Now forget about that lead and go get the next one.",
  "One lead means you've figured out what works. Do it again!",
  "You broke through — now break through again, and again.",
  "That took guts. Now use those same guts on the next call.",
  "First lead is the foundation. Now build something on top of it!",
  "You started — and starting is half the battle. Finish the other half!",
  "The first one always feels special. Make the second one feel even better!",
  "Ice officially broken. Now let's see what you're really made of.",
  "Your first lead of the shift — that's how legends begin.",
  "Great execution on call number one. Call number two is waiting.",
  "You got the first one through sheer determination. Respect. Now get another.",
  "First lead secured. Confidence loaded. Fire away.",
  "That's how you start a shift — with action, not hesitation!",
  "You took the shot and it landed. Take it again!",
  "The dial tone paid off. Keep making it pay.",
  "First transfer of the day is yours! Keep building your count.",
  "You committed to the call and it worked. Keep committing.",
  "One on the board is worth a hundred excuses. No more excuses!",
  "A great shift always starts somewhere. Yours starts right here.",
  "Your very first lead today shows exactly who you are — now show us more!",
  "You turned a cold call into a hot lead. Do it again!",
  "First transfer: proof that your pitch works. Use that proof!",
  "From zero to one is the biggest jump of all. Everything after this is easier.",
  "That lead was your opening move. Now play the whole game!",
  "You've got the first W of the day. Stack more on top of it!",
  "The dial worked. The pitch worked. YOU worked. Do it again!",
  "First transfer logged — your shift has officially begun!",
  "The hardest call is the one you haven't made yet. You just proved you can do it.",
  "That's your opening statement to the floor. Make it a long speech!",
  "From silent to scoring — that's what you just did. Keep going!",
  "You broke your zero. Now let's break your personal best.",
  "Step one complete. The rest of the steps are waiting on you.",
  "That first transfer took grit. Now let grit become your identity today.",
  "You sparked it! Now fan the flame into a fire.",
  "First lead of the day means you refused to wait. That's a winner's mindset.",
  "Great start — the only direction from here is up.",
  "You didn't wait for the perfect call. You made the perfect call.",
  "One transfer logged. One step closer to owning this shift.",
  "Your name is on the board! Now let's make sure it stays there all day.",
  "That lead came from your effort and nothing else. Own it — then do it again.",
  "First one in the bag — now what are you going to do about it?",
  "You broke the ice with nothing but a phone and confidence. Respect!",
  "Starting strong is a choice. You made the right one.",
  "That's a great first step. Ten more of those and you're elite.",
  "First transfer of the shift — you're already in the top half of the room.",
  "The phone works when you do. You proved that. Now prove it again.",
  "First lead: delivered. Next task: get another one — right now.",
  "From no leads to one lead — you made the shift happen. Keep shifting!",
  "Your dial-to-transfer ratio just got a whole lot better. Keep it up!",
  "The board lights up one lead at a time. You just flipped the switch.",
  "Look at that — one lead already and the shift is barely started!",
  "You opened the gate. Now let the numbers pour through.",
  "Great job getting started! The hardest part is behind you now.",
  "First transfer of the day — you're a rep of action, not excuses.",
  "That call paid off because you made it. Never forget that.",
  "Lead one: done. The story of your shift is just beginning.",
  "You got the first one. That one is proof you can get ten more!",
  "First lead secured — the dial tone just became your best friend.",
  "You didn't overthink it, you just did it. That's the whole game right there.",
  "One lead means one thing: your pitch works. Now go use it again.",
  "The first transfer is the hardest mental hurdle. You cleared it — now sprint.",
  "That call mattered. This next one matters more.",
  "You found the yes in all those nos. Go find another one.",
  "First lead of the shift — you belong on this floor and you just proved it.",
  "The dial paid off! Every rep who's ever had a great day started exactly here.",
  "You just turned a phone call into a result. Do it again immediately.",
  "First one through means your voice is working, your pitch is landing, and you're ON.",
  "No excuses, no delays — just one clean transfer. That's a pro.",
  "Your first lead is the match. Now light the whole board on fire.",
  "Done and dusted on number one. Don't let the momentum die here.",
  "You didn't wait for the perfect list. You worked the one you had. Respect.",
  "One lead is all it takes to change the energy of a shift. You did it.",
  "First lead in — that's the signal. Everything after this is built on this moment.",
  "Look at you executing! First one on the board and the shift is just warming up.",
  "That first transfer is the one that matters most. You got it. Now go get another.",
  "You showed up, you dialed, you transferred. That's the whole formula — repeat it.",
  "First lead secured. Now the only question is: how many more?",
  "You took the call seriously and it paid off. Take every call that seriously.",
  "Your first lead is proof that the process works when you work the process.",
  "First one locked — the rest of the day just got a lot easier.",
  "You got through the ice. Now swim.",
  "Every big number on the board today started with a first lead. This is yours.",
  "First transfer means you're already ahead of everyone still waiting for a good call.",
  "The board is waking up and your name is what opened its eyes.",
  "You planted the seed. Now water it with every dial you make.",
  "First lead of the day — the floor just got a little more competitive.",
  "One down and your mindset is clearly in the right place. Stay in it.",
  "The first lead is the key. You've got it. Now open the door all the way.",
  "You turned the first dial that counted today. Keep turning them.",
  "That first transfer is YOUR anchor for the rest of the shift. Build from it.",
  "Lead secured — your confidence just leveled up. Don't waste it.",
  "The shift clicked the moment that first transfer went through. Don't unclick.",
  "First lead in the books — now make the book a bestseller.",
  "You cracked the code on that first call. Same code works on the next one.",
  "From zero to one: the only gap that matters. You crossed it.",
  "First lead through and your energy should be ELECTRIC right now. Use it!",
  "You found the client who was ready. There are more of them in that list.",
  "Lead one: evidence that you know exactly what you're doing.",
  "That first transfer is what separates starters from sitters. You started.",
  "One on the board and the whole shift is ahead of you. How high does this go?",
  "That call paid off because you treated it like it mattered. They all matter.",
  "First lead means first win. Stack the wins.",
  "You're off the mark and there's no looking back. Only forward from here.",
  "The first transfer is a message to yourself: I can do this. Message received.",
  "First lead secured — your shift has officially gone from potential to production.",
  "You didn't wait for a perfect pitch. You pitched and it worked. Do it again.",
  "Lead one is on the board. Lead two is waiting for you to go get it.",
  "That first yes is the spark. Every subsequent call is gasoline.",
  "You're on the scoreboard now. Own every point from here.",
  "First lead means your strategy is solid. Don't overthink it — just execute.",
  "The transfer happened because you kept talking when others would've stopped. That's you.",
  "First one secured — you've officially entered the conversation for top rep today.",
  "Your first lead just told the floor: this rep means business today.",
  "One transfer in and you're already a threat. Imagine what five looks like.",
  "First lead of the shift — the best time to get another is right now.",
  "You made the call count. Make the next one count harder.",
  "Lead one is done. Lead two won't get itself.",
  "First transfer locked in — the shift just shifted in your favor.",
  "You didn't need a lucky call. You needed skill and effort. Both showed up today.",
  "The first lead is a gift you gave yourself by dialing. Keep giving.",
  "That first transfer clears the noise. Now all you need to do is keep dialing.",
  "Your first lead said everything about your mindset today. Keep saying it.",
  "One lead changes the energy of a shift. You just changed yours.",
  "First one through — now your only job is to make the next call immediately.",
  "Lead one: secured. Lead two: your next mission. Go.",
  "You got the ball rolling and now it's gaining speed. Keep pushing.",
  "First transfer in and you're exactly where you need to be. Stay here — and go further.",
  "That first 'transferred' notification? That's the sound of you doing your job perfectly.",
  "One lead is the permission slip you gave yourself to go get five more.",
  "First lead through — you've done the hardest part. Now do the easiest part: dial again.",
  "You put in the work and the board rewarded you. It'll do it again if you keep working.",
  "First lead of the day: proof that your head and your pitch are in the right place.",
  "The lead didn't happen by accident. It happened because you showed up fully. Stay full.",
  "You've got your first one and the whole shift is your canvas. Paint something great.",
  "Lead one is on the board and it's only going up from here. Keep climbing.",
  "That transfer was your announcement to the floor. Make it the first line of a long speech.",
  "First lead done — your name is on the board and it belongs there. Keep it there.",
  "You executed perfectly on that first call. Repetition is all that stands between you and legendary.",
  "One lead means you went from potential to productive. Don't go back to potential.",
  "The first one is always a sigh of relief. Good. Now breathe and go get the next one.",
  "First transfer — you've built the foundation. Now build the whole house.",
  "Your first lead proves one thing: the right attitude + the right pitch = results. Repeat.",
  "Lead one: in the bag. The bag isn't full yet — keep loading it.",
  "You got the first one through sheer will. Now let skill take over.",
  "First lead secured. You've earned every dial that comes after this one.",
  "From the first dial to the first transfer — you stayed committed. Stay committed.",
  "One lead is enough to build a great shift on. Don't stop building.",
  "First one in and you've already set the tone for your day. Keep setting it.",
  "Your first lead just told the leaderboard your name. Give it more reasons to remember you.",
  "Lead one: done with focus and execution. That's your formula. Use it every single call.",
  "First transfer secured — your shift is officially in motion. Keep moving.",
  "You just got the hardest lead of the day out of the way. Everything else is bonus.",
  "Lead one down. The confidence from this call should carry you straight into the next.",
  "First lead = first proof. Proof that today is YOUR day."
];

// ── TIER 2: Building Momentum (2–3 leads, 100 quotes) ──
const QUOTES_BUILDING = [
  "Two leads in and you're already in rhythm — don't stop!",
  "Look at you building momentum! The floor is watching.",
  "You're stacking them up — this is what consistency looks like.",
  "Two transfers and climbing. Your dialer is hot right now!",
  "That's back-to-back execution. Keep the pressure on.",
  "You're finding your groove — now let's make it a pattern.",
  "Three leads? You're officially dangerous today.",
  "Momentum is everything — and you've got it. Ride it!",
  "The calls are paying off. You know what to do — keep dialing!",
  "Look at those numbers growing! You're in the zone.",
  "Two-three leads in and your confidence should be through the roof.",
  "This is what a good shift looks like. Stay focused!",
  "You're on a roll and the day isn't over yet — push harder!",
  "Every lead is proof your pitch is landing. Keep going!",
  "Back-to-back transfers — you're building something real here.",
  "That's consistent execution. The leaderboard is noticing.",
  "You're in the flow now. Don't let anything break your rhythm.",
  "Two or three might not seem like much — but it's more than most!",
  "Each transfer compounds. Stack one more and watch what happens.",
  "You're warming up the board. Keep the heat coming!",
  "That's the kind of momentum that turns an average shift into a great one.",
  "Numbers on the board and you're just getting started — let's go!",
  "You're proving your pitch works. Now prove it again.",
  "The grind is working. Don't you dare let up now.",
  "Two-three leads means you're locked in. Stay there!",
  "Two leads means your pitch is clicking. Don't fix what isn't broken!",
  "You're compounding your effort into results. Keep the compounding going.",
  "Two in and comfortable — that's when reps do dangerous things on the board.",
  "Three transfers and you're already a threat on this leaderboard.",
  "The momentum you have right now is a gift — don't waste it.",
  "Two leads down and your energy is only getting stronger. Keep going!",
  "Consistency is rare. Two-three leads shows you've got it.",
  "You've proven it once and then again. That's not luck — that's skill.",
  "Three leads means three times your pitch landed. It's working. Keep working it!",
  "The leaderboard is looking at you differently after that last lead.",
  "Two-three leads and the shift isn't half over. Where does this end up?",
  "You're stacking evidence that you know how to dial. Stack more!",
  "Each lead you add makes the next one feel more inevitable. Keep proving it.",
  "You're not on a hot streak — you're on a SKILL streak. Big difference.",
  "Three leads is the kind of pace that ends shifts with something to be proud of.",
  "The more leads you get, the more confident your next call will be. Keep building!",
  "You've already outperformed a big chunk of the floor. Don't stop there.",
  "Two-three leads in and your pitch is warming up. Full heat is coming!",
  "This is what momentum feels like — hold onto it and don't let go!",
  "Back-to-back transfers tells everyone on the floor who they should be watching.",
  "You're making the numbers happen, not waiting for them to happen. That's elite.",
  "Two leads in the bag and your confidence is contagious — spread it to the board.",
  "Consistent transfers means consistent effort. You're showing up on every call.",
  "Three leads means three times you controlled the conversation. Do it again!",
  "You're not getting lucky — you're getting good. Those are two very different things.",
  "Two-three leads shows hunger. The hungriest reps always eat well.",
  "Keep riding this wave — it's yours and the whole floor can see it.",
  "The board is starting to tell your story. Make it a good one!",
  "Two-three leads means your system is working. Trust it and keep executing.",
  "You're turning dials into dollars. Don't slow down now!",
  "Three leads already? You're running this floor right now.",
  "The pipeline is flowing because you kept the pressure on. Keep pushing!",
  "Momentum like this doesn't just happen — you built it. Keep building.",
  "Two transfers in and your mindset is clearly in the right place. Stay there!",
  "This is what it looks like when a rep is locked in. Stay locked in.",
  "Three leads means you're eating while others are still warming up their phones.",
  "You're proving with every lead that hard work converts. Don't stop proving it.",
  "Two-three leads is the sweet spot — hungry enough to push, confident enough to close.",
  "Every lead you get makes the next call easier to make. Keep building that confidence.",
  "Two-three leads and a whole lot of shift left. This could be a record day.",
  "The phones are your friend today. Keep making friends.",
  "Two leads means two conversations where YOU were better than the objection.",
  "Three in already — you're dialing with purpose and it shows.",
  "Back-to-back-to-back means you're not leaving anything on the floor today.",
  "The grind is paying off. Don't let up — the grind is just getting started!",
  "Two-three leads in and this shift is already trending upward. Push the trend!",
  "You're in a groove that most reps only dream about. Protect it with every dial.",
  "Three transfers on the board means three times the client said yes to YOU.",
  "Momentum is fragile — protect yours by making the next call right now.",
  "Two-three leads and your name is becoming a regular on that board. Keep it there.",
  "You've got the pace of a top performer today. Finish what you started.",
  "Two leads means your opener is working. Three means your close is too. Elite!",
  "The rep who goes from two to five leads is the one everyone remembers at end of shift.",
  "You're making every dial count. That's what separates good from great.",
  "Three leads and counting — this shift belongs to you if you want it.",
  "Every transfer you make today is an investment in your reputation on this floor.",
  "Two-three leads and your energy is telling on you — in the BEST way possible.",
  "The hustle is visible in your numbers. Keep the hustle alive.",
  "Three leads proves you can do this on repeat. Now prove it even more!",
  "You're dialing with purpose. The results are speaking louder than any excuse could.",
  "Two-three leads and the floor is quietly taking notice. Give them more to notice.",
  "Your work ethic is showing in your numbers today. Let it keep showing!",
  "Three leads in and the shift still has legs — how high can you take this?",
  "You've made three clients' day better today. They don't know it yet — but you do.",
  "This pace doesn't just happen — it comes from showing up on every single call.",
  "Two leads means you're a rep who delivers. Three means you deliver consistently.",
  "You're not coasting — you're building. There's a huge difference and it matters.",
  "Three transfers and still going — this is what a dominant shift looks like.",
  "The board shows two-three leads. Your work ethic shows why it's going higher.",
  "Back-to-back means you're not overthinking it — you're just doing it. Perfect.",
  "Two-three leads and the competition should be worried. Are they?",
  "You've found your rhythm. Now play it louder than anyone else on the floor.",
  "Three leads means three decisions you made correctly under pressure. Respect.",
  "Two leads in and the board is smiling at your name. Give it more reasons to smile.",
  "You're not just working the phones — you're working the room. Keep working it!",
  "Two leads and you're already proving this is no accident — it's ability.",
  "Back-to-back means your opener is solid AND your close is landing. Elite combo.",
  "Three leads already? You're in a different gear than most of the floor right now.",
  "Two in and the rhythm is unmistakable. Protect it with every single dial.",
  "You're stacking leads like you know something the floor doesn't. Keep knowing it.",
  "Two-three leads means two or three clients believed what you said. That's trust. Build more.",
  "The board is reflecting your effort and it looks great. Let's make it look even better.",
  "Three transfers and you haven't looked up from the phones once. That's a grinder.",
  "Two leads in and your pitch is clearly working. Don't mess with what's working.",
  "You've built a streak and streaks are momentum — don't let anything interrupt it.",
  "Three leads says you're not warming up anymore. You're in full production mode.",
  "Two-three in and you're making the floor jealous. Give them more reason to be.",
  "You're converting calls into transfers and that is literally the entire job. You've got it.",
  "Two leads means you found the formula twice. Three means you've mastered it.",
  "Every lead you stack right now is going to look incredible at end of shift. Keep stacking.",
  "You're building something real on that board. Real effort, real results.",
  "Three leads and you haven't let a single objection stop you. That's championship material.",
  "Two-three in and your mindset is clearly dialed in as much as your phone is.",
  "The floor is watching the board and your name keeps showing up. Keep showing up.",
  "You're running on all cylinders — pitch, pace, persistence. All three are working.",
  "Two leads means you've cracked two conversations wide open. Three means you own the skill.",
  "Every time you hit transfer, you're proving this is more than just a good day — it's you.",
  "Three leads and the shift hasn't even peaked yet. That's a terrifying thought for your competition.",
  "Two in and your confidence should be building with every dial. Let it build.",
  "You're not chasing leads anymore — you're collecting them. Keep collecting.",
  "Three leads means you refused to let the floor's energy slow you down. Respect.",
  "Two-three transfers and the pace you're setting is hard to match. Don't let anyone match it.",
  "You're laying down a foundation of production that the whole shift will rest on.",
  "Three leads already means you're going to have a story to tell at end of day. Write it.",
  "Two in and the confidence in your voice on the next call should be through the roof.",
  "You're building a lead count, a reputation, and a great shift — all at the same time.",
  "Three transfers means three perfect executions. You don't execute perfectly by accident.",
  "Two leads says you know your pitch. Three leads says you know your customer. That's elite.",
  "The work is showing up in the numbers and the numbers are showing up on the board.",
  "Two-three in and you're the rep everyone should be watching right now.",
  "Every lead past two is proof you didn't let the first one make you comfortable.",
  "Three leads means you pushed past the relief of the first one and kept grinding. That's character.",
  "You're in the zone where results feed confidence and confidence feeds results. Beautiful.",
  "Two in and your energy is the kind that makes the next call easier before it even starts.",
  "Three leads means three clients said yes to your pitch today. Your pitch is a weapon.",
  "You didn't get lucky twice or three times — you got GOOD. Huge difference.",
  "Two-three leads in and you're doing what most reps wish they could do: staying consistent.",
  "The board tells the story and right now your chapter is the best one on it.",
  "Three leads and you're not slowing down. The floor can feel your pace.",
  "Two in and your focus is visible in your numbers. Don't lose that focus.",
  "You're building the kind of shift that earns respect before it's even over.",
  "Three transfers and each one was earned through skill, not luck. Own that.",
  "Two-three leads means you're on track for something great. Stay on track.",
  "You're converting with consistency and consistency is the hardest skill in this game.",
  "Three leads already and the phones keep ringing. Keep answering them the right way.",
  "Two in and you're ahead of the pace most reps set on their best days.",
  "You're threading calls into leads and leads into momentum. That's the whole art form.",
  "Three transfers on the board and the shift is still going. How far does this go?",
  "Two-three leads means you've found a groove that works. Protect that groove.",
  "Your effort is compounding into results. Let it compound all the way to the end of shift.",
  "Three leads and your confidence on the next call should be absolutely iron-clad.",
  "Two in and you've proven your pitch lands. Three in and you've proven it's repeatable.",
  "You're not counting leads — you're focused on the next call. That's why the leads keep coming.",
  "Three transfers means three wins. In a row. Today. That's not small.",
  "Two leads in and you're setting a pace that will define your shift. Define it well.",
  "You're doing the thing that most reps talk about doing and never quite manage: staying consistent.",
  "Three leads tells me everything about your work ethic today. It's at its best.",
  "Two-three in and the momentum isn't a feeling anymore — it's a fact. It's in the numbers.",
  "You've built a streak worth protecting. Protect it with the next dial.",
  "Three leads means you've beaten every distraction and every slow moment so far today.",
  "Two in and your name is becoming one of the first the floor checks on the board.",
  "Every lead you add now is another brick in what's becoming a standout shift.",
  "Three transfers and you've proven that your skill isn't a fluke — it's a feature.",
  "Two-three leads in and the floor manager is paying attention to you for the right reasons.",
  "You're building lead by lead, call by call. That's how the greats do it.",
  "Three leads already and the best part is you make it look repeatable. Because it IS.",
  "Two in and your voice, your pitch, and your mindset are all aligned. Stay aligned.",
  "You're showing the floor what efficient, purposeful dialing looks like. Keep showing.",
  "Three leads and you haven't wasted a single minute feeling sorry about a rejection.",
  "Two-three in and your production is telling everyone what kind of rep you are. Keep telling.",
  "You're turning the phones into a scoreboard and your score is climbing. Keep scoring.",
  "Three leads means three times the client heard something in your voice they trusted. Build on that.",
  "Two in and every rejection between here and your next lead just got a little easier to handle.",
  "You're stacking results and results stack confidence. You're in the best cycle there is.",
  "Three transfers logged and the shift isn't close to over. The ceiling is wide open.",
  "Two-three leads and you're the benchmark for the floor right now. Set a high bar.",
  "You're not overthinking it. You're not underdoing it. You're just dialing and winning.",
  "Three leads in and you're the proof that good reps find a way no matter the list.",
  "Two in and your second lead came faster than your first. That's momentum — chase it.",
  "You've got two-three leads and a whole lot of shift ahead of you. Build from this foundation.",
  "Three transfers says you've been relentless today. The board rewards relentless. You see it.",
  "Two leads means you've made two people's decision easier today. Make more easier.",
  "You're in building mode and the structure is looking solid. Keep laying the bricks.",
  "Three leads and counting — this is the kind of pace that earns recognition.",
  "Two-three in and you're converting at a rate that speaks for itself. Let it keep speaking.",
  "Your numbers today are a direct reflection of your effort. Your effort is impressive.",
  "Three leads means three times you outworked an objection. You've got more of that in you.",
  "Two in and there's a whole list of people waiting for your pitch. Go give it to them.",
  "You're not hoping for leads — you're creating them. That's the difference between good and great.",
  "Three transfers and your name is the answer to the question: who's killing it today?"
];

// ── TIER 3: On Fire (4–5 leads, 100 quotes) ──
const QUOTES_ON_FIRE = [
  "Four-five leads?! You are absolutely on fire right now!",
  "This is elite-level dialing. You're carrying the floor!",
  "Five leads and climbing — you're the one to beat today!",
  "At this pace you're heading for a legendary shift. Don't stop!",
  "You're not just dialing — you're SELLING. What a performance!",
  "Four leads in and you're dominating the board. Stay hungry!",
  "This is what champions look like in action. Keep grinding!",
  "You've hit your stride and it shows. The leaderboard belongs to you.",
  "Five transfers?! The floor needs to learn your name today.",
  "You are in full beast mode. Do NOT let up!",
  "This pace wins shifts. You're rewriting today's story.",
  "Four-five leads means you've cracked the code. Double down!",
  "You're making it look effortless — this is pure skill on display.",
  "At this level you're not just hitting numbers — you're setting the standard.",
  "Five in? The competition is watching your number climb.",
  "You're in a zone most reps never find. Stay locked in!",
  "Call after call, transfer after transfer — this is your day!",
  "Four leads shows grit. Five leads shows greatness. What's next?",
  "You've separated yourself from the pack. Go even further!",
  "Every objection today is falling to you. Keep attacking those calls!",
  "You've got momentum, confidence, and skill firing all at once. Unstoppable!",
  "The board doesn't lie — and right now it's saying you're elite.",
  "Four-five leads is the kind of shift that gets remembered. Make it count!",
  "You're the standard on this floor right now. Own it!",
  "Half the floor wishes they were where you are. Keep building your lead!",
  "Four leads and you haven't even hit your stride yet. Imagine what's coming next!",
  "Five in and you're rewriting the expectations for this shift. Keep writing!",
  "You're on a pace that legends are built from. Don't stop now.",
  "Four leads means you are absolutely cooking right now. Keep the heat up!",
  "Five transfers already — you're not having a good shift, you're having a GREAT one.",
  "This is elite territory and you belong here. Prove it with the next dial.",
  "Four leads in and the floor is turning to watch. Give them a show!",
  "You're running hot and the board shows it. Keep the temperature up!",
  "Five transfers means five perfect conversations. You're operating at a different level.",
  "At four-five leads your shift is no longer about surviving — it's about dominating.",
  "The top of the leaderboard isn't far off. Are you going after it?",
  "Four leads and climbing — your name is the one everyone is watching.",
  "Five transfers in and you're proving that elite performance isn't an accident.",
  "You've outperformed most of the floor already. What does the rest of the day hold?",
  "Four-five leads means you're not just dialing — you're DELIVERING.",
  "Five in already and you're making it look easy. It's not easy. That's the point.",
  "Your dial count is translating into transfers at an elite level. Keep converting.",
  "Four leads says you showed up. Five leads says you showed OUT.",
  "You're in a class of your own today. No one on this floor is matching your pace.",
  "Five leads and the shift's not over — this is how record days happen!",
  "Four-five transfers means your pitch is basically a weapon at this point.",
  "You're lighting up the board and the whole floor feels the energy you're bringing.",
  "Five in and you're not done — the grind that got you here will take you further.",
  "Four leads means you're elite. Five leads means you're exceptional. What comes next?",
  "You've proven you can hit four and five. Now prove five can become ten.",
  "The scoreboard is screaming your name right now. Are you listening?",
  "Four-five leads and you haven't slowed down once. That's championship-level focus.",
  "Every one of those five transfers came from effort. Own every single one.",
  "You're in the zone where everything is clicking — don't overthink it, just keep dialing.",
  "Five leads means five times you overcame an objection. That's five wins.",
  "The rest of the floor is trying to catch up to where you already are.",
  "Four leads in — you've got the floor's attention. Now take their respect too.",
  "At five leads, you've crossed from good to great. Chase outstanding next.",
  "You're setting the pace for the entire floor right now. Run faster.",
  "Four-five in and your confidence is a weapon now. Use it on the next call.",
  "Five transfers — you're not participating in this shift anymore, you're WINNING it.",
  "The pace you're keeping right now is what turns a good day into a legendary one.",
  "Four leads proves you can do it consistently. Five proves you can keep going.",
  "You've found the formula today: dial, pitch, close, repeat.",
  "Five in and you're the example the floor manager points to when they say 'do that.'",
  "Four-five leads and the energy you're bringing is contagious. The floor feels it!",
  "You're creating your highlight reel one transfer at a time. Keep rolling the tape.",
  "At this count you're not chasing the board anymore — you're running it.",
  "Five leads means five clients who connected with your pitch. You're elite at this.",
  "Four in already and the best part? You're just getting warmed up.",
  "Five transfers shows precision. Shows skill. Shows heart. Keep showing all three.",
  "You've separated from the pack. Now put some real distance between you and them.",
  "Four-five leads means your work rate is elite. Your mindset clearly matches it.",
  "Five leads and the shift is YOURS if you want it. How badly do you want it?",
  "At this pace you're the most dangerous rep on the floor. Act like it.",
  "Four leads and counting — this is what peak performance looks like in real time.",
  "Five transfers already means you've been locked in from the first dial. Incredible!",
  "You are not slowing down. Good. Don't.",
  "Four-five leads and you haven't peaked yet — scary thought for the competition.",
  "Every one of those leads was earned through grit, skill, and discipline. Remember that.",
  "At five leads you're telling a story on that board. Make it the best story of the day.",
  "Four in and your momentum is building. The best reps let momentum work for them.",
  "Five transfers — you're doing everything right today. Don't stop doing everything right.",
  "The shift could've gone any direction. You pointed it straight to the top.",
  "Four leads means you've cracked four different conversations. You're getting good at this.",
  "Five in and counting — you're officially one of the big names on the floor today.",
  "This is the pace of a true top performer. Protect it and push it further.",
  "Four-five leads and the shift is still going. Give that number nowhere to go but up.",
  "You are cooking right now and the whole floor can smell it. Keep cooking.",
  "Five transfers in and the board is basically your personal property today.",
  "Four leads means four perfect pitches under pressure. Do it one more time.",
  "At five leads you're not just a rep — you're a performance.",
  "You've hit the kind of pace that managers talk about in team meetings. Keep delivering.",
  "Four-five in and you haven't flinched once. Ice runs through your veins right now.",
  "Five leads and you're still going? The floor is watching a masterclass unfold.",
  "Four leads says you're locked in. Five leads says you're elite. Six says you're a legend.",
  "You're operating at a frequency most reps never reach. Don't come down from it.",
  "Five transfers and you're making it look like this is the only pace you know. Keep it.",
  "Four in and every subsequent call is building on the confidence of the last win.",
  "You're on the kind of streak that defines shifts and sometimes careers. Keep going.",
  "Five leads means five clients are better off than they were before your call. Own that.",
  "Four-five in and your name on the board is standing out like a spotlight. Stay bright.",
  "You're not warming up at five leads — you're fully ON. Stay fully on.",
  "Four leads in and the floor's energy shifted when your count climbed. Feel that.",
  "Five transfers means your pitch is working, your close is landing, and you are unstoppable.",
  "At this count you're not just competing — you're setting the standard others compete against.",
  "Four-five leads and you're dialing with a purpose that most reps can't maintain.",
  "Five in and the best thing you can do right now is forget the count and make one more call.",
  "Four leads means you've executed perfectly four times in a row under real pressure.",
  "You're at the level where the effort becomes automatic. Keep letting it be automatic.",
  "Five transfers and your track record today is already the kind reps wish they had.",
  "Four-five in and you're proving that high performance isn't reserved for a special few.",
  "You've made five clients take action today. That's real impact. Keep making an impact.",
  "Four leads and you're dialing like someone who has something to prove. You've proven it — now prove more.",
  "Five in and your energy is the loudest thing in this call center right now.",
  "At four-five leads you've crossed into territory where the best reps separate from the rest.",
  "You're not surviving the shift — you're dominating it. Stay in domination mode.",
  "Five transfers already means you're building a highlight reel nobody can ignore.",
  "Four leads and the competition is either inspired by you or intimidated by you. Either way, you win.",
  "You've made five transfers and the session clock is still ticking. This is YOUR time.",
  "Four-five in and you've already guaranteed yourself a shift worth being proud of.",
  "Five leads means you outlasted every quiet spell and every tough objection. Five times.",
  "At this pace you're going to look back at the end of shift and feel incredible.",
  "Four leads in and you're dialing with the precision of someone who has figured this out.",
  "Five transfers — the floor is talking about your count. Give them more to talk about.",
  "Four-five leads and your name at the top of that board isn't luck. It's labor.",
  "You're not waiting for good calls anymore. You're MAKING good calls. Big difference.",
  "Five in and the momentum you've built is a living breathing thing. Feed it.",
  "Four leads means four times the client chose to trust you over hanging up. Earn that trust again.",
  "At five leads your work speaks for itself. Let it keep speaking.",
  "Four-five in and you're the example of what maximum effort looks like. Be that example.",
  "You've got five transfers and a full tank of fuel. Don't leave anything in that tank.",
  "Four leads in and every dial you make from here is adding to something impressive.",
  "Five transfers is the kind of result that shifts conversations from 'average' to 'excellent.'",
  "Four-five in and you've proven that this floor, this list, this shift — it's all yours.",
  "You're at five leads and the phones are still warm. Keep them warm.",
  "Four leads and your pitch is a machine right now. Don't tinker with a running engine.",
  "Five transfers in and you haven't let a single moment go to waste today. That's elite.",
  "Four in and the distance between you and the middle of the pack is growing. Pull further ahead.",
  "At five leads your effort today is already the answer to every excuse you'll never make.",
  "Four-five in and the whole floor is measuring themselves against your count.",
  "You're building a shift that other reps will reference when they talk about great days.",
  "Five leads and you're not just on fire — you're the benchmark. Burn brighter.",
  "Four in and every next call is a chance to add to something genuinely impressive.",
  "Five transfers means your consistency is the story of the day. Keep writing the story.",
  "Four-five leads and you haven't burned out, slowed down, or made excuses. That's rare.",
  "You've hit five and you look like you're just getting started. Terrifying for the competition.",
  "Four leads means four times the clock worked in your favor because YOU worked.",
  "Five in and your discipline on this shift is showing in every single lead on that board.",
  "Four-five transfers and you're reminding the floor what it looks like to really compete.",
  "You're operating on a different level and the count proves it. Stay at that level.",
  "Five leads means you pushed through five rounds of pressure and won every single one.",
  "Four in and you're the kind of rep who makes this job look like it was made for them.",
  "At five leads you've earned the right to set the tone for the rest of this floor.",
  "Four-five in and the board is telling the story of a rep who came here to win.",
  "You've transferred five times today. Five clients are closer to their goals because of you.",
  "Four leads and your name at the top of the board has a nice ring to it. Keep ringing.",
  "Five in and you're showing the floor that great shifts are built, not gifted.",
  "Four-five leads means you turned your potential into production. That's the whole game.",
  "You've earned every one of those five transfers. Own them and go earn more.",
  "Four leads in and the floor's best rep is clearly the one still dialing.",
  "Five transfers and you're deep in a groove that most reps only find for a moment.",
  "Four-five in and you've turned this shift into a statement. Make the statement louder.",
  "You're at five leads and the only question left is: what's the number at end of shift?",
  "Four leads already and the best part? The board still has room for more of your name.",
  "Five transfers means you spent every minute of this shift doing one thing: producing.",
  "Four-five in and your output today is something to point to when people ask what's possible.",
  "You've hit five and the floor can feel the energy you're carrying. Don't put it down.",
  "Four leads means four clients heard something in your voice that made them trust the process.",
  "Five in and you've separated yourself from the field. The only race left is with your own best.",
  "Four-five transfers and you are the living definition of what this floor is capable of.",
  "You're at five leads and every rep on this floor is benchmarking against your number.",
  "Four in and you haven't let a single dead call slow your roll. That's mental strength.",
  "Five transfers — it's not about having a great day. It's about MAKING a great day. You made it.",
  "Four-five in and the board is yours to own. Take ownership.",
  "You've built five leads on nothing but skill, effort, and consistency. That's everything.",
  "Four leads in and the shift is still running. So are you. Don't stop running.",
  "Five transfers logged — your dial-to-transfer rate is doing some serious talking right now.",
  "Four-five in and you're reminding everyone why they should be dialing harder.",
  "You're at five leads and this shift has officially become a story worth telling.",
  "Four leads in and your momentum has a life of its own. Let it carry you further.",
  "Five transfers and you've made it clear: when you show up, you SHOW UP.",
  "Four-five leads and you've answered the question every rep has to face: can I perform consistently? Yes. Yes you can."
];

// ── TIER 4: Legend Mode & Call Center Motivation (6+ leads, 100 quotes) ──
const QUOTES_LEGEND = [
  "Every dial is a new chance to change your life. Never stop calling.",
  "The phone is the only tool you need to win today. Use it.",
  "Call centers are built by reps who refuse to quit. Be that rep.",
  "Rejection isn't failure — it's just the price of the next transfer.",
  "The more you dial, the luckier you get. Keep going.",
  "In this game, consistency beats talent. Show up on every call.",
  "Every 'no' you hear is someone else's 'yes' getting closer.",
  "The best reps don't wait for motivation — they create it with every dial.",
  "Your voice is your weapon. Use it with confidence on every call.",
  "Volume solves everything. When in doubt — dial more.",
  "Top performers in this industry share one trait: they never stop dialing.",
  "A transfer isn't luck — it's the result of 20, 30, 50 dials. You earned it.",
  "The phone doesn't know you're tired. Dial like you're fresh.",
  "Your pitch gets stronger with every single call you make. Trust the process.",
  "Call centers reward one thing above all else: relentless effort. Keep it up.",
  "You're not just making calls — you're building a career one transfer at a time.",
  "Today's grind is tomorrow's glory. Every transfer counts.",
  "The top of the leaderboard is lonely — because not everyone is willing to work for it.",
  "One more dial could be the one. You'll never know unless you make it.",
  "Champions in this business are made between the rejections. Push through.",
  "A great rep doesn't wait for a hot list — they make every list hot.",
  "Stay on script, stay confident, stay dialing. Results follow the relentless.",
  "The floor is yours if you want it. What are you willing to do to take it?",
  "In sales, activity is everything. The more you do, the more you get.",
  "Your best call hasn't happened yet. Keep dialing until it does.",
  "In a call center, effort is currency. You're rich today. Keep spending.",
  "Six leads and you've officially entered the conversation for top performer of the day.",
  "The phone rings for a reason. Every rep who answers it has a chance. You're taking yours.",
  "Elite reps don't have better days — they have better standards. Yours are showing.",
  "This level of production takes guts, skill, and relentlessness. You have all three.",
  "Six-plus leads and you're running the floor now. Don't give up the lead.",
  "The best call center reps share one trait: they make one more call when others stop.",
  "You're outworking, outperforming, and outproducing the competition. Keep going.",
  "Every lead past five is a bonus that most reps never claim. You're claiming yours.",
  "A call center legend isn't born — they're built, one transfer at a time. Like you.",
  "Six leads means you stayed the course when others broke from it. Respect.",
  "The grind is a test. Every lead past six proves you're passing it.",
  "You're not just on the board — you're the board right now. Protect your position.",
  "The phone is the great equalizer. Skill and effort win. You're proving both.",
  "Six-plus leads is what happens when preparation meets relentless execution.",
  "You've built something special today. Don't leave before you've seen what it becomes.",
  "In this industry, activity always wins. You're the most active rep right now.",
  "The dial tone doesn't care how you feel. But you dial anyway. That's a pro.",
  "Six leads means the system is working because YOU are working. Keep working!",
  "Call centers don't build legends from the top — they build them from the grind. That's you.",
  "Every rep who dials enough eventually finds their rhythm. You found yours.",
  "Six-plus leads and your effort is compounding into results. Let it compound.",
  "A great call center rep knows: the next call is always the most important one.",
  "You're creating momentum that the whole floor feels. Use it. Share it. Keep building.",
  "The call center floor rewards persistence above everything else. You're being rewarded.",
  "Six-plus leads means you're showing what's possible. Others will dial harder because of you.",
  "When you stop counting and just keep dialing — that's when the numbers really take off.",
  "Every transfer you make is a result, a win, and a reminder of what you're capable of.",
  "The reps who get to 6+ leads are the ones who don't overthink between calls.",
  "Six leads means six different people heard your pitch and said yes. That's an art.",
  "You didn't wait for a good list or a good mood. You made a good day. Own it.",
  "The top performers in call centers share one secret: they dial when no one else will.",
  "Six-plus leads and you're not done. In this game you are never done.",
  "Your persistence is your pitch. Your follow-through is your close. You've got both.",
  "Six leads says you treated every call like it was the first one of the day. That's elite.",
  "The call center floor belongs to the consistent. You are consistent. You belong here.",
  "Six-plus leads means every 'no' today brought you closer to the 'yes' that just happened.",
  "You are the example of what happens when you commit to the process completely.",
  "Six leads and still going — you're what every floor manager wishes for in a rep.",
  "The transfer rate that top performers have isn't magic. It's volume plus skill.",
  "Six-plus leads means you're converting at a level that's hard to argue with.",
  "Your best shift ever is the one you're currently building. Don't stop building it.",
  "A rep with six leads is dangerous. One who keeps dialing past six is unstoppable.",
  "Call centers are built on reps like you — relentless, consistent, and results-driven.",
  "Six leads means you've mastered the art of turning conversations into conversions.",
  "Every dial is a data point. Your data today says you're exceptional.",
  "Six-plus leads and you're proving the doubters wrong with every single dial.",
  "The best call center skill isn't the pitch — it's the courage to pick up the phone after rejection.",
  "Six leads means you've outlasted every obstacle, every objection, and every slow period today.",
  "You're the rep other reps are talking about today. Make sure they can't stop talking.",
  "Six-plus leads tells the story of a rep who came to work today with a purpose.",
  "The floor has rhythms — and you found one today that's working. Ride it to the end.",
  "Persistence is what separates the good from the great. You're squarely in great.",
  "Six leads and the phones keep ringing. The difference? You keep picking up.",
  "You're building the kind of shift that gets referenced in future training sessions.",
  "Six-plus leads means you turned every rejection into fuel. You've got a full tank.",
  "The call center is a battlefield. Six leads means you've won six battles today.",
  "Your consistency today is a message to the floor: this is how it's done.",
  "Six leads — if you keep dialing at this pace, you'll be the name everyone remembers.",
  "The top of the leaderboard wasn't built in one call. You've been building it all shift.",
  "Six-plus leads means you're producing results, not excuses. That's a career.",
  "In call centers, the ones who break records do it one dial at a time. You're doing that.",
  "Six leads and counting — at this point the shift is yours. Don't give it back.",
  "You didn't just show up today — you showed UP. The board reflects every bit of your effort.",
  "Six-plus leads and the floor can feel your energy. Don't let it drop.",
  "Call centers run on transfers. You're the engine powering this floor right now.",
  "Six leads means your mindset, pitch, and effort are all aligned. That's unstoppable.",
  "The rep who makes one more call when they're tired is the rep who wins the shift.",
  "Six-plus in and you've officially written yourself into the history of this shift.",
  "The rep who hits 6+ leads didn't find a secret. They found a standard. Theirs is high.",
  "You're not on a hot streak — you're in a hot season. Keep it going.",
  "Six leads and counting: this is what it looks like when someone refuses to stop.",
  "At this level, every dial is a declaration: I am not done. Make that declaration.",
  "Six-plus leads means you've faced down rejection all shift and won every single time.",
  "You've built the kind of count that shifts the energy of the entire floor. Own that.",
  "Six leads in and the only thing standing between you and legendary is more dials.",
  "At this point, the question isn't whether you can hit more — it's how many more you want.",
  "Six-plus transfers and you are the floor right now. Act accordingly.",
  "Every rep who's ever had a career day started right where you are. Keep going.",
  "Six leads means six times the client chose to say yes to you. That's a gift — and a skill.",
  "You've hit six and the shift has fuel left. The ceiling is wherever you put it.",
  "Six-plus in and your name on that board is no longer just a name — it's a statement.",
  "The reps who reach six leads don't do it by accident. They do it by refusing.",
  "Six leads means you gave this shift everything you had and then gave it a little more.",
  "At 6+ leads you've crossed from participant to champion. Compete at champion level.",
  "Six-plus transfers and the grind that got you here is now a habit. Keep the habit.",
  "You're in legend territory and the board reflects every call it took to get here.",
  "Six leads in and your consistency today is the rarest thing on this floor. Protect it.",
  "At this level you're not just producing — you're setting the tone for what's possible.",
  "Six-plus transfers means you found a gear most reps don't know they have. Stay in it.",
  "You've earned every lead on that board with nothing but effort and execution.",
  "Six leads and still dialing — that's not a good day, that's a great rep in action.",
  "The further you push past six, the more the floor remembers this shift. Keep pushing.",
  "Six-plus leads means every slow moment, every tough objection — you beat all of it.",
  "At this count your dial button is probably warm to the touch. Keep pressing it.",
  "Six leads and your name belongs at the top of the board. Keep putting it there.",
  "You've proven today that the best reps aren't born — they're built, one dial at a time.",
  "Six-plus in and the floor's energy shifted the moment your count climbed this high.",
  "Every rep on the floor should be dialing harder because of what your count says.",
  "Six leads means six different conversations where you were simply better. Keep being better.",
  "At 6+ leads you've created a standard for yourself today. Don't fall below it.",
  "Six-plus transfers and you're turning raw effort into raw results. Pure excellence.",
  "You've hit six and the story of your shift is still being written. Make it epic.",
  "Six leads in and you are the answer to the question: what does a top performer look like?",
  "At this level every dial is an investment in your reputation on this floor. Keep investing.",
  "Six-plus leads means your closing muscle is fully developed. Use it on every call.",
  "You've outlasted fatigue, slow periods, and bad calls to get to six leads. Respect.",
  "Six leads and the floor is taking notes on your performance. Give them more to study.",
  "At 6+ your name at the top of the board isn't a surprise — it's inevitable.",
  "Six-plus transfers and you're producing results that will be the benchmark for a long time.",
  "You've reached a point in this shift where every lead is just proof you refuse to quit.",
  "Six leads means the floor's standard just got raised by one rep — you.",
  "At this count, the question is simple: how many more dials can you make before end of shift?",
  "Six-plus in and you've made this floor better just by the way you showed up today.",
  "You've hit six leads and proved that the top of the board is where you belong.",
  "Six leads means six reasons for your team to believe in what's possible today.",
  "At 6+ leads you're not just winning your shift — you're inspiring everyone watching.",
  "Six-plus transfers and the legend of this shift will be your story. Finish it strong."
];

// ── TIER 2B: Exactly 2 Leads (100 quotes) ──
const QUOTES_2_LEADS = [
  "Two leads on the board — you're not just started, you're building!",
  "Back-to-back transfers. That's not luck, that's skill.",
  "Two in and the shift just took a different shape. A better one.",
  "You got your first and then you went and got another. That's a winner's move.",
  "Two leads means you didn't let the first one be the last one. Now go for three.",
  "That second lead just proved the first wasn't a fluke. You've got this.",
  "Two on the board and your pitch is clearly clicking. Don't stop clicking.",
  "Back-to-back baby! The floor is noticing. Keep making them notice.",
  "Two transfers in and your momentum is real. It's in the numbers.",
  "You doubled your count — now triple it.",
  "Two leads means you did it once, caught your breath, and did it again. That's grit.",
  "That second transfer is the one that tells the story. And your story is just getting started.",
  "Two in and the confidence you have right now should be weapons-grade. Use it.",
  "Back-to-back execution. You know what they say — three's the charm.",
  "Two leads and the board just started paying close attention to your name.",
  "That's two calls that went exactly the way they were supposed to. Do it again.",
  "Two transfers logged — your dialer is hot and so is your pitch. Keep both going.",
  "You went from one lead to two. Now go from two to four.",
  "Two in and you're already above average for this shift. Aim higher.",
  "Back-to-back means your technique is repeatable. Repeat it until the shift ends.",
  "Two leads in and you've proven this isn't a one-call wonder. You've got range.",
  "That second lead came because you didn't celebrate the first one too long. Good.",
  "Two transfers means two clients heard something they believed. Be believable again.",
  "You doubled up and now the only move is to keep going. So keep going.",
  "Two in and your name is one of the ones worth watching right now.",
  "Back-to-back transfers and you haven't even hit your stride yet. Scary.",
  "Two leads means you've already outpaced a lot of this floor. Don't let them catch up.",
  "That second transfer should feel even better than the first. Now make the third feel better than the second.",
  "Two on the board and the dial tone is calling you back. Answer it.",
  "You got two and you're not even winded. Go get three.",
  "Two leads in — that's momentum with a capital M. Protect it.",
  "Back-to-back success is the foundation of a great shift. You've laid it.",
  "Two transfers and your pitch is a repeatable machine right now. Run the machine.",
  "You went 1, then 2. The sequence only goes one direction from here.",
  "Two in and the confidence you've earned on these calls should carry you straight into the next.",
  "That's two for two today. Keep the perfect record going.",
  "Two leads means two wins. In a row. Today. That's your story right now.",
  "Back-to-back and still going — your consistency is already the best thing on this floor.",
  "Two transfers in and you've proven you can do this not just once, but repeatedly.",
  "You hit two and the floor is watching your number to see where it goes. Show them.",
  "Two in and the momentum isn't slowing down — it's speeding up. Let it.",
  "That second lead is the one that makes people sit up and notice. They're noticing.",
  "Two leads on the board means the third is already within reach. Go reach for it.",
  "You've stacked two transfers and the pitch is getting sharper with every call.",
  "Back-to-back is the hardest thing to do on a call center floor. You made it look easy.",
  "Two in and you haven't let a single rejection slow your roll. That's professional.",
  "Two transfers means two times you controlled the conversation all the way to the close.",
  "You doubled up fast. The floor respects the rep who doesn't sit on their first lead.",
  "Two leads in and you're dialing with the energy of someone who has nothing to lose and everything to gain.",
  "Back-to-back transfers — that's not a start, that's a STATEMENT.",
  "Two in and the best thing you can do is pretend you only have one and go get another.",
  "Two leads means you found the yes twice today. It's out there again. Go find it.",
  "You've got two and a whole lot of shift left. How many more can you get?",
  "Back-to-back and building — the board is starting to say your name louder.",
  "Two transfers in and your resolve on the phones is showing in every digit of that count.",
  "Two leads means two moments where your voice convinced someone to take action.",
  "You got your second and it means everything. It means you can keep going.",
  "Two in and the dialer is hot, the pitch is tight, and the close is landing. Perfect trifecta.",
  "Back-to-back means you figured out how to repeat yourself. Now repeat yourself again.",
  "Two leads in and this shift is bending in your direction. Help it bend further.",
  "You went from one to two without missing a beat. Don't miss the next beat.",
  "Two transfers on the board — your name is starting to own some real estate up there.",
  "Two in and your head is in the right place. Keep it there.",
  "Back-to-back transfers today means your pitch is working at a high level. Trust it.",
  "Two leads down and you haven't looked back once. That's exactly right.",
  "Two in and your phone is an instrument you're playing beautifully today.",
  "You scored twice and the half isn't even over. Imagine the final count.",
  "Two transfers means two times you got a stranger to trust your pitch. That's magic — but it's yours.",
  "Back-to-back and the floor can feel your energy. Don't drop the energy.",
  "Two leads in and the second one means you didn't coast on the first. That's maturity.",
  "You're two in and it's clear: today you came to work, not just to show up.",
  "Two transfers and your confidence right now is the most powerful thing in this building.",
  "Back-to-back means you executed the same formula twice. Execute it five more times.",
  "Two in and your second lead is the one that separates the producers from the one-and-dones.",
  "You hit two and the tone of your shift changed permanently. For the better.",
  "Two leads on the board and you've made your case to be taken seriously today.",
  "Back-to-back transfers — that's two decisions you made correctly under live pressure.",
  "Two in and the rhythm is there. The formula is there. The results are there. Keep it all there.",
  "You didn't wait for the right call to get your second lead. You made the call right.",
  "Two transfers and you're running a pace most reps dream of hitting at some point today.",
  "Two leads in and the board is reflecting exactly what you've been putting in. Keep putting in.",
  "Back-to-back means you're consistent and consistent is the most valuable word in this room.",
  "Two in and you've outworked every excuse you could've made. That's character.",
  "Two leads and the best part? You don't look satisfied. Good. Don't be. Go get more.",
  "You're two for the shift and it's clearly your day. Make it your day all the way to close.",
  "Back-to-back transfers — the floor respects the rep who builds, not just the one who starts.",
  "Two in and you're doing the thing that matters most: staying disciplined between calls.",
  "Two leads means you closed two different conversations the right way. Your process is solid.",
  "You hit your second lead and the momentum you have right now is a gift from yourself to yourself.",
  "Two in and every rep watching the board just saw your count climb. Keep climbing.",
  "Back-to-back and the leaderboard has you as someone to watch. Give them more to watch.",
  "Two transfers in and you're making today count in the most important way: with results.",
  "Two leads means two wins. And in this game, wins compound. Let yours compound.",
  "You've hit two and you look dangerous. You ARE dangerous. Prove it with the next dial.",
  "Two in and your pace says you're here for a great shift — not just a decent one.",
  "Back-to-back transfers means back-to-back moments where you were at your absolute best.",
  "Two leads down and the only thing between you and three is a dial and a pitch. Go.",
  "You've got two leads and a whole lot of shift ahead. The math is in your favor.",
  "Two in — you're already writing a shift worth talking about. Don't stop writing.",
  "Two leads in and you've made your presence known on this floor. Now make it undeniable."
];

function pickQuote(count, isFirst) {
  let pool;
  if (isFirst || count <= 1)   pool = QUOTES_FIRST_LEAD;
  else if (count === 2)        pool = QUOTES_2_LEADS;
  else if (count <= 3)         pool = QUOTES_BUILDING;
  else if (count <= 5)         pool = QUOTES_ON_FIRE;
  else                         pool = QUOTES_LEGEND;
  return pool[Math.floor(Math.random() * pool.length)];
}

const PRIVATE_ALERT_MESSAGES = [
  "Great transfer! Keep your momentum going. 🔥",
  "You're doing excellent work — stay focused and keep dialing. ⚡",
  "Strong result just now. Keep that same energy! 💪",
  "Nice job! Keep pushing and finish the shift strong. 🚀",
  "Beautiful execution on that call — keep it rolling. 🎯"
];

function normalizeName(name) {
  return String(name || '').trim().toLowerCase().replace(/\s+/g, ' ');
}

function trimTeamPrefix(name) {
  const parts = String(name || '').trim().split(/\s+/);
  if (parts.length <= 1) return String(name || '').trim();
  const first = parts[0].toUpperCase();
  if (/^[A-Z]{2,4}$/.test(first) || /^GY[BP]$/.test(first)) return parts.slice(1).join(' ');
  return String(name || '').trim();
}

function isSameAgentName(a, b) {
  const na = normalizeName(a);
  const nb = normalizeName(b);
  if (!na || !nb) return false;
  if (na === nb) return true;
  return normalizeName(trimTeamPrefix(a)) === normalizeName(trimTeamPrefix(b));
}

function getFirstName(fullName) {
  if (!fullName) return 'Rep';
  const parts = fullName.trim().split(/\s+/);
  if (parts.length > 1 && parts[0].length <= 3 && /^[A-Z]+$/.test(parts[0])) return parts[1];
  return parts[0];
}

function resolveViewerIdentity() {
  const sessionName = sessionStorage.getItem('currentAgentName') || '';
  let profileName = '', profileYtelId = '';
  try {
    const profile = JSON.parse(sessionStorage.getItem('currentAgentProfile') || '{}');
    if (profile) {
      profileName   = profile.name   || '';
      profileYtelId = profile.ytelId || '';
    }
  } catch (e) {}
  alertViewerName   = normalizeName(sessionName || profileName);
  alertViewerYtelId = String(profileYtelId || '').trim();
}

function isViewerAgent(agentObj) {
  if (alertViewerYtelId && agentObj.ytelId) {
    return String(agentObj.ytelId).trim() === alertViewerYtelId;
  }
  return isSameAgentName(agentObj.name || '', alertViewerName);
}

function findViewerEntry(agentsArr) {
  if (!agentsArr || !agentsArr.length) return null;
  if (alertViewerYtelId) {
    const byId = agentsArr.find(a => String(a.ytelId || '').trim() === alertViewerYtelId);
    if (byId) return byId;
  }
  if (alertViewerName) {
    return agentsArr.find(a => isSameAgentName(a.name || '', alertViewerName)) || null;
  }
  return null;
}

function checkLeadAlerts(newAgents) {
  if (!newAgents || !newAgents.length) return;

  const viewerRole = sessionStorage.getItem('bizUserRole') || 'agent';
  const isAdmin    = viewerRole === 'admin';

  resolveViewerIdentity();

  // Build snapshot keyed by agent name
  const tracker = (newAgents[0] && newAgents[0].berbiceTracker) || {};
  let snapshot = Object.keys(tracker).length ? { ...tracker } : {};
  newAgents.forEach(a => {
    if (!a || !a.name) return;
    if (snapshot[a.name] === undefined || snapshot[a.name] === null) {
      snapshot[a.name] = a.dailyLeads || 0;
    }
  });
  if (!Object.keys(snapshot).length) return;

  // ── First load: seed counts, show welcome-back for agent only ──
  if (!leadAlertInitialized) {
    Object.entries(snapshot).forEach(([n, c]) => { prevLeadCounts[n] = c; });
    leadAlertInitialized = true;

    if (!isAdmin && (alertViewerName || alertViewerYtelId)) {
      const ownAgent = findViewerEntry(newAgents);
      const ownCount = ownAgent ? (Number(ownAgent.dailyLeads) || 0) : 0;
      if (ownCount > 0) {
        const firstName = getFirstName(ownAgent.name);
        const quote     = pickQuote(ownCount, false);
        const plural    = ownCount === 1 ? '' : 's';
        _renderAlert({
          icon: ownCount === 1 ? '🥇' : '🔥',
          name: 'Welcome back, ' + firstName + '!',
          msg:  'You currently have ' + ownCount + ' lead' + plural + ' today. Keep going!',
          quote,
          firstLead: ownCount === 1
        });
      }
    }
    return;
  }

  // ── Subsequent polls: detect new leads ──
  const newReps = [];
  Object.entries(snapshot).forEach(([name, count]) => {
    const c    = Number(count) || 0;
    const prev = Number(prevLeadCounts[name]) || 0;
    if (c > prev) {
      const agentObj = newAgents.find(a => a.name === name) || { name };
      newReps.push({ name, count: c, isFirst: prev === 0, agentObj });
    }
    prevLeadCounts[name] = c;
  });

  if (!newReps.length) return;

  if (newReps.length === 1) {
    const { name, count, isFirst } = newReps[0];
    const firstName = getFirstName(name);
    const quote     = pickQuote(count, isFirst);
    const plural    = count === 1 ? '' : 's';
    const msg       = isFirst
      ? firstName + ' just got their FIRST lead of the day! 🥇'
      : firstName + ' just transferred — now at ' + count + ' lead' + plural + ' today! 🔥';
    _renderAlert({ icon: isFirst ? '🥇' : '🔥', name: firstName + ' — New Lead!', msg, quote, firstLead: isFirst });
  } else {
    const hasFirst  = newReps.some(r => r.isFirst);
    const icon      = hasFirst ? '🥇' : '⚡';
    const title     = newReps.length + ' New Leads Just Hit the Floor!';
    const agentList = newReps.map(r => {
      const fn     = getFirstName(r.name);
      const plural = r.count === 1 ? '' : 's';
      return r.isFirst
        ? fn + ' (1st lead! 🥇)'
        : fn + ' (' + r.count + ' lead' + plural + ')';
    }).join('  •  ');
    const maxCount = Math.max(...newReps.map(r => r.count));
    const quote    = pickQuote(maxCount, hasFirst);
    _renderAlert({ icon, name: title, msg: agentList, quote, firstLead: hasFirst });
  }
}

function _renderAlert({icon, name, msg, quote, firstLead = false}) {
  const banner = document.getElementById('lead-alert-banner');
  const inner  = banner.querySelector('.lab-inner');
  if (firstLead) { inner.classList.add('first-lead'); } else { inner.classList.remove('first-lead'); }
  document.querySelector('.lab-icon').textContent = icon;
  document.getElementById('lab-text').innerHTML =
    escapeHtml(name) + '<span>' + escapeHtml(msg) + ' — ❭' + escapeHtml(quote) + '❮</span>';
  banner.classList.add('show');
  document.body.style.paddingTop = '72px';
  startTabBlink(icon + ' ' + name + (firstLead ? ' — First Lead Today!' : ' — New Lead!'));
}

function dismissLeadAlert() {
  document.getElementById('lead-alert-banner').classList.remove('show');
  document.body.style.paddingTop = '';
  stopTabBlink();
}

updateDashboard();
setInterval(updateDashboard, 10000);
