const assert = require('node:assert/strict');
const C = require('../js/time-off-core.js');
const now = Date.parse('2026-10-08T15:00:00-04:00');
const input = { type: 'dayoff', date: '2026-10-09', endDate: '2026-10-10', allDay: true, notes: 'Family commitment' };
const bb = C.create(input, { userId: '101', fullName: 'Alice', team: 'Berbice' }, now);
assert.equal(bb.team, 'BB'); assert.equal(bb.status, 'Requested'); assert.equal(bb.revision, 1);
assert.equal(C.create(input, { ytelId: '102', name: 'Beth', team: 'Providence' }, now).team, 'PR');
assert.throws(() => C.validate({ ...input, notes: ' ' }, now), /reason/);
assert.throws(() => C.validate({ ...input, date: '2026-10-07' }, now), /past/);
assert.throws(() => C.validate({ ...input, endDate: '2026-10-08' }, now), /valid/);
assert.throws(() => C.validate({ ...input, date: '2026-02-30' }, now), /valid/);
assert.throws(() => C.validate({ ...input, type: 'late' }, now), /hours/);
assert.throws(() => C.validate({ ...input, type: '__proto__' }, now), /type/);
assert.throws(() => C.create(input, { userId: '../101', fullName: 'Alice', team: 'BB' }, now), /verified/);
const timed = { ...input, allDay: false, endDate: input.date, time: '09:00', endTime: '11:00' };
assert.equal(C.validate(timed, now).endTime, '11:00');
assert.throws(() => C.validate({ ...timed, endTime: '08:00' }, now), /after/);
assert.throws(() => C.validate({ ...timed, endTime: '' }, now), /both/);
assert.throws(() => C.validate({ ...timed, date: '2026-10-08', endDate: '2026-10-08' }, now), /past/);
assert.equal(C.validate({ ...timed, time: '23:00', endTime: '01:00', endDate: '2026-10-10' }, now).endDate, '2026-10-10');
assert.equal(C.overlaps(timed, bb), true);
assert.equal(C.overlaps(timed, { ...timed, time: '11:00', endTime: '12:00' }), false);
assert.equal(C.overlaps(timed, { ...timed, time: '10:59' }), true);
const actor = { role: 'admin', id: 'manager', name: 'Manager' };
const approved = C.transition(bb, 1, 'Approved', actor, 'Enjoy your day.', now + 1000);
assert.equal(approved.status, 'Approved'); assert.equal(approved.reviewNote, 'Enjoy your day.');
assert.equal(approved.notes, bb.notes); assert.equal(approved.agentId, bb.agentId);
assert.equal(C.transition(approved, 1, 'Declined', actor, 'Concurrent review', now), undefined);
assert.equal(C.transition(bb, 1, 'Approved', { role: 'agent', id: '101' }, '', now), undefined);
assert.equal(C.transition(bb, 1, 'Cancelled', { role: 'agent', id: '102' }, '', now), undefined);
assert.equal(C.transition(bb, 1, 'Cancelled', { role: 'agent', id: '101' }, '', now).status, 'Cancelled');
assert.equal(C.transition(approved, 2, 'Cancelled', { role: 'agent', id: '101' }, '', now), undefined);
assert.throws(() => C.transition(bb, 1, 'Declined', actor, '', now), /reply/);
assert.equal(C.flatten({ '101': { r1: approved, wrong: { ...approved, agentId: '102' } } }).length, 1);
assert.equal(C.flatten({ '101': { r1: approved } })[0].id, 'request:101:r1');
console.log('Time-off core: validation, time ranges, team identity, ownership, cancellation and stale approval checks passed.');
